apiVersion: v1
kind: ConfigMap
metadata:
  name: resilience-config
  namespace: ${NAMESPACE}
data:
  # Bulkhead 설정
  BULKHEAD_DEFAULT_MAX_CONCURRENT_CALLS: "50"       # 기본 최대 동시 요청 수
  BULKHEAD_DEFAULT_MAX_WAIT_DURATION: "500"         # 기본 최대 대기 시간(ms)

  BULKHEAD_MART_MAX_CONCURRENT_CALLS: "100"         # MART 최대 동시 요청 수
  BULKHEAD_MART_MAX_WAIT_DURATION: "500"            # MART 최대 대기 시간(ms)

  BULKHEAD_CONVENIENCE_MAX_CONCURRENT_CALLS: "200"   # CONVENIENCE 최대 동시 요청 수
  BULKHEAD_CONVENIENCE_MAX_WAIT_DURATION: "300"      # CONVENIENCE 최대 대기 시간(ms)

  BULKHEAD_ONLINE_MAX_CONCURRENT_CALLS: "50"        # ONLINE 최대 동시 요청 수
  BULKHEAD_ONLINE_MAX_WAIT_DURATION: "1000"         # ONLINE 최대 대기 시간(ms)

  # Retry 설정
  RETRY_COUNT: "3"                               # 실패 시 재시도 횟수
  RETRY_STATUSES: "BAD_GATEWAY,SERVICE_UNAVAILABLE" # 재시도를 유발하는 HTTP 상태 코드
  RETRY_METHODS: "GET,POST"                      # 재시도를 적용할 HTTP 메소드
  RETRY_FIRST_BACKOFF: "5000"                    # 첫 번째 재시도까지 대기 시간(ms)
  RETRY_MAX_BACKOFF: "20000"                     # 최대 재시도 대기 시간(ms)
  RETRY_FACTOR: "2"                              # 재시도 간격 증가 배수
  RETRY_BASED_ON_PREVIOUS: "false"               # 이전 대기시간 기반 증가 여부

  # Rate Limiter - MART
  RATE_MART_LIMIT: "100"                         # MART 유형의 초당 최대 요청 수
  RATE_MART_REFRESH: "1"                         # MART 제한 새로고침 주기(초)
  RATE_MART_TIMEOUT: "5"                         # MART 요청 제한 시 대기 시간(초)

  # Rate Limiter - CONVENIENCE
  RATE_CONVENIENCE_LIMIT: "200"                  # CONVENIENCE 유형의 초당 최대 요청 수
  RATE_CONVENIENCE_REFRESH: "1"                  # CONVENIENCE 제한 새로고침 주기(초)
  RATE_CONVENIENCE_TIMEOUT: "2"                  # CONVENIENCE 요청 제한 시 대기 시간(초)

  # Rate Limiter - ONLINE
  RATE_ONLINE_LIMIT: "50"                        # ONLINE 유형의 초당 최대 요청 수
  RATE_ONLINE_REFRESH: "1"                       # ONLINE 제한 새로고침 주기(초)
  RATE_ONLINE_TIMEOUT: "10"                      # ONLINE 요청 제한 시 대기 시간(초)

  # Circuit Breaker
  CB_SLIDING_WINDOW_SIZE: "10"                   # 장애 감지를 위한 요청 수집 윈도우(건수) 크기
  CB_FAILURE_RATE_THRESHOLD: "50"                # 서킷 오픈을 위한 실패율 임계값(%)
  CB_WAIT_DURATION_IN_OPEN: "30000"              # 서킷 오픈 상태 유지 시간(ms)
  CB_PERMITTED_CALLS_IN_HALF_OPEN: "5"           # Half-Open 상태에서 허용할 시험 요청 수